use_calib: True
single_thread: False
dataset:
  subsample: 2
  img_downsample: 1
  center_principle_point: True

matching:
  max_iter: 10
  lambda_init: 1e0
  convergence_thresh: 1e-6
  dist_thresh: 1 # distance in 3D space
  radius: 1
  dilation_max: 5 # Right now starts from max and iteratively decreases until 1

tracking:
  min_match_frac: 0.00
  max_iters: 50
  C_conf: 0.0
  Q_conf: 1.5
  rel_error: 1e-3
  delta_norm: 1e-3
  huber: 1.345
  match_frac_thresh: 0.3
  sigma_ray: 0.003
  sigma_dist: 1e+1
  sigma_pixel: 1.0
  sigma_depth: 1e+1 # NOTE: log-depth!
  sigma_point: 0.05
  pixel_border: -10 # Only in calib (negative means allow pixels outside image up to that distance)
  depth_eps: 1e-6 # Only in calib case
  filtering_mode: weighted_pointmap # recent, first, best_score, weighted_pointmap, weighted_spherical, indep_conf
  filtering_score: median # median, mean (only used for filtering_mode=best_score)

local_opt:
  pin: 1
  C_conf: 0.0
  Q_conf: 1.5
  min_match_frac: 0.0
  pixel_border: -10000 # Only in calib (negative means allow pixels outside image up to that distance)
  depth_eps: 1e-6 # Only in calib case
  max_iters: 10
  sigma_pixel: 0.0005
  sigma_depth: 1e+1 # NOTE: log-depth!
  delta_norm: 1e-8 # useless in the current implementation
  use_cuda: True

retrieval:
  k: 10
  min_thresh: 0.0

ms_opt:
  # NOTE: It is recommended to just use this setting or slightly tune it.
  imu_noise: [ 0.00001962, 0.00001028445124575, 0.00004905, 0.00000036361026075] # accel_noise_sigma, gyro_noise_sigma, accel_bias_rw_sigma, gyro_bias_rw_sigma
  init_bias_noise: [0.01,0.01,0.01,0.000001,0.000001,0.000001]
  regularization_noise: [0.01,0.01,0.01,1,1,1]
  enable_excalib: False
  subpixel_factor: 4
  d_diff_threshold: 1.0
  window_num: 10 
  imu_format: 'custom_deg' # 'custom_deg', 'custom_rad', 'subt' 

loop:
  conf_noise_along: 0.25
  conf_noise_cross: 0.10
  interest_distance: 8.0 

global_opt:
  imu_noise: [ 0.00001962, 0.00001028445124575, 0.00004905, 0.00000072722052150] # accel_noise_sigma, gyro_noise_sigma, accel_bias_rw_sigma, gyro_bias_rw_sigma


