width: 640
height: 480
# With distortion (fx, fy, cx, cy, k1, k2, p1, p2)
calibration:  [758.3153257832925, 676.6492212772476, 318.27111164892506, 239.79816832491474, 1.583106303248484, -0.059098218173967695, 0.1793477408661115, 0.0016819528105368057, -0.0005887999624264534]
model: mei
scale: 0.4

Tic:
  - [-0.04279531, -0.00237969,  0.99908103,  0.19499356]
  - [-0.99880330, -0.02359508, -0.04283961,  0.04340662]
  - [ 0.02367534, -0.99971877, -0.00136708, -0.01782382]
  - [ 0.00000000,  0.00000000,  0.00000000,  1.00000000]

# %YAML 1.2
# ---
# rgb_camera_to_imu:
#   rows: 4
#   cols: 4
#   data: [-0.04279531, -0.00237969,  0.99908103,  0.19499356
#          -0.99880330, -0.02359508, -0.04283961,  0.04340662
#           0.02367534, -0.99971877, -0.00136708, -0.01782382
#           0.00000000,  0.00000000,  0.00000000,  1.00000000]


# %YAML 1.2
# ---
# rgb_camera:
#   model_type: MEI
#   camera_name: camera
#   image_width: 640
#   image_height: 480
#   mirror_parameters:
#     xi: 1.583106303248484
#   distortion_parameters:
#     k1: -0.059098218173967695
#     k2: 0.1793477408661115
#     p1: 0.0016819528105368057
#     p2: -0.0005887999624264534
#   projection_parameters:
#     gamma1: 758.3153257832925
#     gamma2: 676.6492212772476
#     u0: 318.27111164892506
#     v0: 239.79816832491474
  

# %YAML 1.2
# ---
# rgb_camera_to_imu:
#   rows: 4
#   cols: 4
#   data: [-0.04279531, -0.00237969,  0.99908103,  0.19499356
#          -0.99880330, -0.02359508, -0.04283961,  0.04340662
#           0.02367534, -0.99971877, -0.00136708, -0.01782382
#           0.00000000,  0.00000000,  0.00000000,  1.00000000]

# %YAML 1.2
# ---
# rgb_camera:
#   model_type: MEI
#   camera_name: camera
#   image_width: 640
#   image_height: 480
#   mirror_parameters:
#     xi: 1.583106303248484
#   distortion_parameters:
#     k1: -0.059098218173967695
#     k2: 0.1793477408661115
#     p1: 0.0016819528105368057
#     p2: -0.0005887999624264534
#   projection_parameters:
#     gamma1: 758.3153257832925
#     gamma2: 676.6492212772476
#     u0: 318.27111164892506
#     v0: 239.79816832491474