width: 1392
height: 512
# With distortion (fx, fy, cx, cy, k1, k2, p1, p2)
calibration:  [788.629315, 786.382230, 687.158398, 317.752196, -0.344441, 0.141678, 0.000414, -0.000222, -0.029608]

Tic:
  - [0.99944133,-0.00228419,-0.03334389,-0.03734697]
  - [0.03268308,-0.14183394,0.98935078,1.75837780]
  - [-0.00698916,-0.98988784,-0.14168005,0.59911765]
  - [0.00000000,0.00000000,0.00000000,1.00000000]